### ISSUE TITLE
Activity: Add one update and collapse two Stages per v5 of the SLE Transition Chart

### ISSUE THREAD

**Issue by douglaswyatt** [adityadigitalomnibus/goliath#12]

**Comment by adityadigitalomnibus** [comment]
I did not understand this bug. In our shared folder, we only have v4 of the SLE transition chart. I could not find any V5. And as per v4, the updates and stages are correct. Can you please remove all other versions and update the one which is the latest and correct one.

**Comment by douglaswyatt** [comment]
I can't right now but I think I either emailed it to you or attached it to the bug.  If you can't find it, I'll send it again when I get back on Tuesday night.

Doug

**Comment by adityadigitalomnibus** [comment]
Please check your mail. I still didn't get it. Can you update it in the drive folder if you are back. Also, please add more bugs to this tracker. I want to be done with all bugs before our call on Thursday.

**Comment by douglaswyatt** [comment]
I just added v5 to the shared folder…

**Comment by adityadigitalomnibus** [comment]
Fixed according to v6 doc.
