### ISSUE TITLE
Case / Activity: Update list panel doesn't display on Case/Activity view page

### ISSUE THREAD

**Issue by douglaswyatt** [adityadigitalomnibus/goliath#14]
I've got to click on the panel for it to show up.  Might be Mac specific, but it happens in Safari, Firefox and Chrome.

**Comment by douglaswyatt** [comment]
![screen shot 2016-12-27 at 12 04 08 pm](https://cloud.githubusercontent.com/assets/23498712/21494561/602be18c-cc38-11e6-8f6f-7e383ac3d932.png)

**Comment by adityadigitalomnibus** [comment]
It is mac specific. Its happening because your browser is not maximised and hence this being a responsive platform is adapting to your browser size.
