### ISSUE TITLE
Case: the Petitioner/Respondent/Client UI elements are too complicated.  I think they need to be converted to just simple text fields.

### ISSUE THREAD

**Issue by douglaswyatt** [adityadigitalomnibus/goliath#15]
Users have complained and I think I agree with them.  It's just too complicated to use.  So I'd convert them to simple text fields.  I'd have one for Petitioner, one for Respondent and two for client - name and contact info.

**Comment by douglaswyatt** [comment]
Also the Clerk field.  It should just be a single "select a user" field (like owner, but only allow one person to be in the field).

**Comment by adityadigitalomnibus** [comment]
changed the UI to textboxes instead of modal windows

**Comment by douglaswyatt** [comment]
The new text boxes are good, but you only created one for the Client, instead of two (one for name and one for contact info).

**Comment by douglaswyatt** [comment]
As of Feb 24, there are 3 boxes for Client - name, email and pnhone number.  that's good.  For petitioner and respondent, one field is good enough.  So I think it's fine now.
