### ISSUE TITLE
Profile: I sometimes get a 404 Not Found error when I click on the Profile link

### ISSUE THREAD

**Issue by douglaswyatt** [adityadigitalomnibus/goliath#16]
I think it's only when logged in as Kabir, but not sure.

It's this URL (http://hrln-tool.org/user/profile.html)

**Comment by douglaswyatt** [comment]
I also get it sometimes when logged in as Doug, but haven't seen it yet when logged in as Aditya.

**Comment by adityadigitalomnibus** [comment]
Fixed. Please re-open this if this bug arises again. This should not come now.
