### ISSUE TITLE
Case/Activity: clear up confusion between Primary Unit and Group as per 9-Nov-2016 email

### ISSUE THREAD

**Issue by douglaswyatt** [adityadigitalomnibus/goliath#18]
"I just realized, in going through the Activity Specification document, that we seem to have confused/merged the Primary Group and Unit fields in the Case management system.  On the Creation page, it’s called “Primary Unit”, when it should be “Primary Group” (and this will likely be an Initiative, not a Unit).  And the Unit field does not exist (but should be defaulted to the Unit of the person creating it).  The Unit is a geographical group that describes the office out of which the Case (or Activity) is being litigated/managed, while the Primary Group describes the subject matter (e.g. Housing Rights).  Looking at the Specification table, they are two separate fields, the Primary Group being any type of Group, while the Unit is restricted to Unit groups.  Sorry I missed this earlier."

**Comment by adityadigitalomnibus** [comment]
Will be taken up in next phase of development. Its a major change to the system. Made a note of it in the development tracker sheet

**Comment by douglaswyatt** [comment]
Can we at least change the name of the current field to Primary Group instead of Primary Unit, then in the next phase we can add the Unit field and get the rest of it fixed up?

**Comment by adityadigitalomnibus** [comment]
Changed the name.

**Comment by douglaswyatt** [comment]
Confirmed fixed.
