### ISSUE TITLE
Users: Last login date/time in user list for admins as per 9-Nov-2016 email

### ISSUE THREAD

**Issue by douglaswyatt** [adityadigitalomnibus/goliath#19]
"Also, it occurred to me that it would be nice to keep track of the date/time of last login for each user, and display that in the User List/Profile page.  Is that easy to add in the second milestone?"

**Comment by adityadigitalomnibus** [comment]
Now tracking the date/time of last login and showing it in admin panel - user management

**Comment by douglaswyatt** [comment]
Confirmed fixed.
