### ISSUE TITLE
Activity Creation: unlike most other list-selection fields, the activity type cannot be selected by arrow-down to the correct one and then hitting tab.  

### ISSUE THREAD

**Issue by douglaswyatt** [adityadigitalomnibus/goliath#24]
Tab does nothing then.  Hitting return works though.

**Comment by adityadigitalomnibus** [comment]
I selected it by arrow-down and hitting tab. didn't have to press enter key. Not sure, why its happening at your end. Can you please check and confirm. I am closing it for now. If its still there, please re-open it and I will connect with you on teamviewer to check.

**Comment by douglaswyatt** [comment]
Still happens for me on Safari and Chrome (but works correctly on Firefox)

**Comment by douglaswyatt** [comment]
(If I hit tab on this field, it just changes the form focus to the next field, primary unit)

**Comment by douglaswyatt** [comment]
Seems to work (if I hit F, it changes to Fact Finding, and then if I hit Tab, it sticks).  So confirmed.
