### ISSUE TITLE
Activity: The events/stages are a bit too complicated. 

### ISSUE THREAD

**Issue by douglaswyatt** [adityadigitalomnibus/goliath#26]
I've simplified them (removed a few events and changed the names and possible events) for a couple of the stages and create a new (v6) for the chart and added it to the shared drive.

**Comment by douglaswyatt** [comment]
Also note - some of the shaded cells (for activities that can occur but which don't change the stage) have been changed as well.

**Comment by adityadigitalomnibus** [comment]
changes made according to v6
