### ISSUE TITLE
Activity/Case Update: Form title should be changed.

### ISSUE THREAD

**Issue by douglaswyatt** [adityadigitalomnibus/goliath#28]
Creation form should have a 2-line title that includes "Adding Update to <Activity/Case Name>", followed by "Current Stage: <current stage>".  For Activities, I would include the Activity Type in brackets after the Activity Name.  And the text should be bold and black. Currently it doesn't include the name, and the type is incorrectly displayed at the bottom, and the text is light colored so it's not as prominent as it should be.

**Comment by douglaswyatt** [comment]
![screen shot 2016-12-27 at 12 24 35 pm](https://cloud.githubusercontent.com/assets/23498712/21494965/e7e2993e-cc3a-11e6-9156-51931951e4ca.png)

**Comment by adityadigitalomnibus** [comment]
fixed. Please check if the new look and format works or not.

**Comment by douglaswyatt** [comment]
yes - looks good.
