### ISSUE TITLE
Activity Update: if I add a person more than once to as a participant, it shows up in the list twice.  It should not.

### ISSUE THREAD

**Issue by douglaswyatt** [adityadigitalomnibus/goliath#29]
![screen shot 2016-12-27 at 12 37 04 pm](https://cloud.githubusercontent.com/assets/23498712/21494980/0327a5c2-cc3b-11e6-8fa2-fcd0a89e1113.png)

**Comment by douglaswyatt** [comment]
![screen shot 2016-12-27 at 12 37 20 pm](https://cloud.githubusercontent.com/assets/23498712/21494985/11752438-cc3b-11e6-980a-aaed45d725bf.png)

**Comment by adityadigitalomnibus** [comment]
Fixed. even it you can select multiple in the view, only one entry will be stored. This duplicate participant problem is resolved.

**Comment by douglaswyatt** [comment]
OK - major problem is fixed,  but would be nice if it doesn't let you try to add them twice on the form.  Looks odd...but agree not a major issue.
