### ISSUE TITLE
Activity/Case Update: need notice for why some updates can't be deleted

### ISSUE THREAD

**Issue by douglaswyatt** [adityadigitalomnibus/goliath#30]
The system correctly prevents you from deleting any but the most recent Update.  But it should also indicate on these Updates why there is no Delete button so users aren't confused as to why they sometimes see it and sometimes don't.  In place of the Delete Update button, just a simple note indicating "Only the most recent Update can be deleted"

**Comment by adityadigitalomnibus** [comment]
Mentioned the note

**Comment by douglaswyatt** [comment]
I don't see the note

**Comment by douglaswyatt** [comment]
Seems to exist in cases, but not Activities.

**Comment by douglaswyatt** [comment]
fixed
