### ISSUE TITLE
Case/Activity Updates: the date of the Case or Activity Update is always listed/displayed as the date it was added to the system, even if I selected a different date when creating it.

### ISSUE THREAD

**Issue by douglaswyatt** [adityadigitalomnibus/goliath#33]
We should store the date/time that it was added for Audit-trail purposes, but for display to the user, it should be the date that they selected when creating it.  And it should not have a time associated with it (since they don't select a time when they pick the date)

**Comment by adityadigitalomnibus** [comment]
change the date

**Comment by douglaswyatt** [comment]
This is broken for Activities, though seems to be fixed for Cases.  This worries me though - this is shared functionality between Cases and Activities (and any other future SLEs).  So the fact that it's broken in one and working in another makes me fear that there's more replicated code than I'd hope for.

**Comment by douglaswyatt** [comment]
Seems fixed as of today.
