### ISSUE TITLE
Profile: When I went to Aditya's Profile page, I saw all the Activities.  

### ISSUE THREAD

**Issue by douglaswyatt** [adityadigitalomnibus/goliath#41]
When I went to a different page and came back, I saw only Aditya's.  This seems related to the other problem I logged re: Doug seeing all of them the first time he logs in after someone else was logged in.  When I clicked on different pages and went back to the profile over and over, about half the time I saw all the Activities on the My Open Activities page, and about half the time I saw only Aditya's.

**Comment by douglaswyatt** [comment]
I cleared my browser (Chrome) cache, logged in as Aditya and on the opening Profile page, I saw other people's activities in the "My Open Activities".  For that matter, I also saw closed activities (i.e. activities in the "Completed" state) - though that is a separate bug, I guess.
![screen shot 2017-02-02 at 3 22 52 pm](https://cloud.githubusercontent.com/assets/23498712/22544647/be314e3a-e95b-11e6-8224-1e71478a5607.png)

**Comment by douglaswyatt** [comment]
Oddly enough, I then clicked to see all the Activities, and then went back to the Profile page and I still saw them all.  Then I clicked on the Cases icon to test a different bug, and was kicked out and asked to log in again.  When I logged in again, I got a profile page that does indeed show only Aditya's cases.  This makes me worried about how caching works.  Why was I able to log in and click around to various pages before being kicked out and then told to re-log in?

**Comment by adityadigitalomnibus** [comment]
thats because we are testing and developing here and we are using the same account. I will give you a go ahead on when you can test, when we are not doing any development. You can check then, One by one. sounds good?

**Comment by douglaswyatt** [comment]
Still a bug for me.

**Comment by douglaswyatt** [comment]
Same as 11

**Comment by douglaswyatt** [comment]
Appears to be fixed.
