### ISSUE TITLE
M2: Case List Page: Canceled cases don't seem to show up

### ISSUE THREAD

**Issue by douglaswyatt** [adityadigitalomnibus/goliath#58]
I created a case, added some updates, and then closed it as "Canceled".  IT showed up in the Report (in the Closed Cases table), but on the Goliath UI, I could not find it in the All Cases search table.  If I went to the Report page, and Viewed the report, then it showed up in the Closed Cases table.  There I could click on it, delete the last update ("un-canceling" it), and then it would show up in the All Cases search list.  All cases, including closed/canceled cases, should show up in the All Cases list.  Only in the "My Open Cases" table on the profile page should it filter out closed/canceled cases.

**Comment by adityadigitalomnibus** [comment]
Completed. Please check and close

**Comment by douglaswyatt** [comment]
Seems to be fixed for cases.  I will test for activities and log that separately if it is a bug.
