### ISSUE TITLE
M2: Report XLS Column Order incorrect in Created and Closed Activities

### ISSUE THREAD

**Issue by douglaswyatt** [adityadigitalomnibus/goliath#59]
According to the spec, the Created Date, Closure Date and Update Date should be the column right to the left of the Related Case column in the three Activity tables.  It is correct in the Update table, but it is to the right of the Related case column in the Created and Closed tables.

**Comment by adityadigitalomnibus** [comment]
Completed. Please check and close.

**Comment by douglaswyatt** [comment]
Fixed.
