### ISSUE TITLE
Activity: When the left hand column (with Activity info and updates in it) isn't wide enough, the Update Type wraps incorrectly.

### ISSUE THREAD

**Issue by douglaswyatt** [adityadigitalomnibus/goliath#6]
It wraps the text, but doesn't get taller, so part of it is cut off.
![screen shot 2016-12-02 at 3 38 23 pm](https://cloud.githubusercontent.com/assets/23498712/20830757/0d5fc606-b8a8-11e6-84ca-3f7fe92d6666.png)

**Comment by adityadigitalomnibus** [comment]
![notabug](https://cloud.githubusercontent.com/assets/24258213/21065289/789926f0-be85-11e6-93bc-435830f34fdf.png)
Its not happening on my end...It may be macbook specific...I will have to check this.

**Comment by douglaswyatt** [comment]
Confirmed fixed on both Chrome and Safari
