### ISSUE TITLE
M2: There is an Activity with an Update that I cannot edit

### ISSUE THREAD

**Issue by douglaswyatt** [adityadigitalomnibus/goliath#66]
I was trying to edit the description of a closed activity to test bug 56, but could not.  Related to a recently logged bug, it's an activity that does not show up in the Activity List for some reason (but does show up in the Report list).  But when I tried to edit the last Update for the Activity, the edit button has been disabled.

activityId=S1MLBa0Gg

![screen shot 2017-03-22 at 4 59 34 pm](https://cloud.githubusercontent.com/assets/23498712/24195739/fe8cbb1e-0f20-11e7-9439-1d689143612d.png)

**Comment by adityadigitalomnibus** [comment]
We are not able to replicate this issue at our end. I logged in from your account and went to the mentioned activity and I was able to access this button. Can you please check it again and tell me if you still find this bug?

**Comment by douglaswyatt** [comment]
It still happens for me.  I log in as you (aditya@goliath.com) in Chrome and go to:
http://hrln-tool.org/admin/activity-view.html?activityId=S1MLBa0Gg
and then click on the most recent Update and see the same picture as above (the Edit button is visibl).  but I cannot click on it.

For what its worth, this is the HTML related to that part of the page:

![screen shot 2017-04-03 at 10 55 46 am](https://cloud.githubusercontent.com/assets/23498712/24596322/22cb6766-185c-11e7-8280-e1bb9f083383.png)

**Comment by douglaswyatt** [comment]
This activity no longer seems to exist.  But I see this bug on a different Activity:
http://hrln-tool.org/admin/activity-view.html?activityId=H1uBSckSe

And here is the HTML for the relevant part of the page:
![screen shot 2017-05-19 at 3 49 42 pm](https://cloud.githubusercontent.com/assets/23498712/26243838/e62873c6-3caa-11e7-8304-72468193ea5d.png)

**Comment by douglaswyatt** [comment]
Still a bug with the activity I linked to in the last update of this bug report.  Edit this Update button does not do anything (using Chrome in an Incongnito window).

**Comment by douglaswyatt** [comment]
The edit button, when not intended to be active, is now invisible, which is good.  But the access control rules are not implemented correctly, so I'll log a separate bug on this.
