### ISSUE TITLE
M2: The Activity SLE transition table is not implemented correctly

### ISSUE THREAD

**Issue by douglaswyatt** [adityadigitalomnibus/goliath#67]
I have an Activity in "Developing Final Plan" stage.  According to the latest SLE Transition table (v7), Project Canceled should be an available Update.  But it is not.  This should be fixed, but I also worry that there may be other cases of slight inconsistencies with the table - and it would be a total pain for me to test by hand.  How is this table implemented in the code?  is it possible to do a complete verification to make sure that all of the Stages allow all of the correct Updates?

![screen shot 2017-03-22 at 5 02 17 pm](https://cloud.githubusercontent.com/assets/23498712/24195900/91d8db5a-0f21-11e7-878f-3ed00e4cfbd9.png)

**Comment by douglaswyatt** [comment]
It also won't let me cancel an activity in the Awaiting Approval stage.

**Comment by adityadigitalomnibus** [comment]
I checked the google drive folder. There is no V7 document in that. I don't think you have shared that with us.

**Comment by douglaswyatt** [comment]
Ah, I guess I never added that one.  Though the bug is true even using the old versions of the file (I think back to the original version).  I added v7 - it just adds a couple more "required document flags" to some of the Activity Updates and renames one of the stages.  There's a couple of comments at the bottom of the activity sheet that describe the changes.  But this bug does not depend on v7.

**Comment by douglaswyatt** [comment]
This one particular one is fixed (the Project Canceled update was missing).  But see bug 71 for others.
