### ISSUE TITLE
M2: All Update Deletions should require a confirmation

### ISSUE THREAD

**Issue by douglaswyatt** [adityadigitalomnibus/goliath#7]
Just like Case, Case Update and Activity deletion.

**Comment by adityadigitalomnibus** [comment]
Changed. Please refresh the page multiple times to clear the cache if any.

**Comment by douglaswyatt** [comment]
This does not appear to have been fixed, so I'm reopening it.

**Comment by douglaswyatt** [comment]
Actually, it appears that Activity Updates do require confirmation before deletion, but Case Updates do not.  All Cases, Activities and Updates of any sort need to have a confirmation before delete.  It appears from my comment at the top of this bug that Case Updates originally did require a confirmation on delete, but now they don't seem to.

**Comment by douglaswyatt** [comment]
Seems fixed.
